/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

import styled from '../../../styles/styled-components/packages/ui/src/styles/styled-components';
export default styled;
import { css } from '../../../styles/styled-components/packages/ui/src/styles/styled-components';
export { css };
