/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

import styled from '../../../styles/styled-components/styled-components';
export default styled;
import { css } from '../../../styles/styled-components/styled-components';
export { css };
